plugins {
    id 'com.android.application'
}

android {
    namespace 'com.netbeta.browser'
    compileSdk 36

    defaultConfig {
        applicationId "com.netbeta.browser"
        minSdk 21
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            manifest.srcFile 'src/AndroidManifest.xml'
            res.srcDirs = ['src/res']
            java.srcDirs = ['src/main/java']
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.10.0'
}
